
[general]
import = [
  # To change theme:
  # > task -g change-theme
  "/usr/share/alacritty/themes/oxocarbon.toml"
]


[font]
size = 13.0

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[terminal.shell]
#args = ["-l", "-c", "tmux attach || tmux new -s main"]
#args = ["-l", "-c", "tmux"]
program = "/bin/zsh"

# [shell]
# program = "/bin/zsh"
# args = ["-l", "-c", "tmux has-session -t main 2>/dev/null && (tmux list-sessions | grep -q 'main:.*attached' && tmux new-session -d -s temp && tmux switch-client -t temp || tmux attach -t main) || tmux new -s main"]


[window]
decorations = "None"

[terminal]

